language: ruby
bundler_args: "--without production"
rvm:
  - 2.2.4
deploy:
  api_key:
    secure: FOY+zwMtK8t5jmHisGUN7c+tUaRuiEXPFg/CF1+MjqpCtR3BwKQ4M+FV8+We1nsOZCH0nlDIHpp8BIu4jNlyMiiKDxzrXHdF5nSSCbrRLsr4+c2a3NYgq6Hl2NDkwvsEF/XO8yWyFnwxjxfi9SF1RWOeS5xwwO5RVxHP4JeBMUrBHxLw2ylPl16aeM0yq+zk+7ZfvY1yrVQk7xyqGJ/tNGVyBOq4U/LlMSrkENVV0IjNV3E1edbX9U8XgvosGcGrTeq7B9oosJT/nUUkYa2uU4/wqAZBqtbQol6v2LMUY77oaR13Qwvazz8j910R/C+G1RC+dcagJpPVGvChg0eI3ESZvrV7Ujwty8NIwQASUXBbmpYIcjjW16hEurYJwfWclSs9y5mfb3woS8Rj3uTGuXv/3aZGjJl0tD/g16MTICTv+oAj5zoWCdQkBt8XMaNq32Ex+HkZB40rlAwO63qhg0hb7YrqMU/wo29W3XhxWlND4b7W7TMAR2Zgz9duXfFh6cY7t4VWG1Y3ZeGQOYDVleTp5MmR+oxRyeLMZSGtsPmJiVX+E5LKslVoLjW/AnXunR9733DuC57gsVJ4fwJM6yjbtb7UOYjt81zWU2Tzq349ouBLRUbadSL5ct3ZhW6GHK6+7Q5dxbFked/VeZTJ+AC114G4LA2YmMxG1eVOFuM=
