require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AnalysesController, type: :controller do

  login_admin


  let(:valid_attributes) {
    build(:analysis).attributes
  }

  let(:invalid_attributes) {
    a=create(:analysis).attributes
    a["dataset_id"] = nil
    a
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnalysesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all analyses as @analyses" do
      analysis =create(:analysis, user: @user)
      get :index, {}
      expect(assigns(:analyses)).to eq([analysis])
    end
  end

  describe "GET #show" do
    it "assigns the requested analysis as @analysis" do
      analysis = create(:analysis, user: @user)
      get :show, {:id => analysis.to_param}
      expect(assigns(:analysis)).to eq(analysis)
    end
  end

  describe "GET #new" do
    it "assigns a new analysis as @analysis" do
      get :new, {}
      expect(assigns(:analysis)).to be_a_new(Analysis)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Analysis" do
        expect {
          post :create, {:analysis => valid_attributes}
        }.to change(Analysis, :count).by(1)
      end

      it "assigns a newly created analysis as @analysis" do
        post :create, {:analysis => valid_attributes}
        expect(assigns(:analysis)).to be_a(Analysis)
        expect(assigns(:analysis)).to be_persisted
      end

      it "redirects to the created analysis" do
        post :create, {:analysis => valid_attributes}
        expect(response).to redirect_to(Analysis.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved analysis as @analysis" do
        post :create, {:analysis => invalid_attributes}
        expect(assigns(:analysis)).to be_a_new(Analysis)
      end

      it "re-renders the 'new' template" do
        post :create, {:analysis => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end


  describe "DELETE #destroy" do
    it "destroys the requested analysis" do
      analysis = create(:analysis)
      expect {
        delete :destroy, {:id => analysis.to_param}
      }.to change(Analysis, :count).by(-1)
    end

    it "redirects to the analyses list" do
      analysis = create(:analysis)
      delete :destroy, {:id => analysis.to_param}
      expect(response).to redirect_to(analyses_url)
    end
  end

end
