require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AssumptionsController, type: :controller do
  login_user
  # This should return the minimal set of attributes required to create a valid
  # Assumption. As you add validations to Assumption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssumptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all assumptions as @assumptions" do
      assumption = Assumption.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:assumptions)).to eq([assumption])
    end
  end

  describe "GET #show" do
    it "assigns the requested assumption as @assumption" do
      assumption = Assumption.create! valid_attributes
      get :show, {:id => assumption.to_param}, valid_session
      expect(assigns(:assumption)).to eq(assumption)
    end
  end

  describe "GET #new" do
    it "assigns a new assumption as @assumption" do
      get :new, {}, valid_session
      expect(assigns(:assumption)).to be_a_new(Assumption)
    end
  end

  describe "GET #edit" do
    it "assigns the requested assumption as @assumption" do
      assumption = Assumption.create! valid_attributes
      get :edit, {:id => assumption.to_param}, valid_session
      expect(assigns(:assumption)).to eq(assumption)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Assumption" do
        expect {
          post :create, {:assumption => valid_attributes}, valid_session
        }.to change(Assumption, :count).by(1)
      end

      it "assigns a newly created assumption as @assumption" do
        post :create, {:assumption => valid_attributes}, valid_session
        expect(assigns(:assumption)).to be_a(Assumption)
        expect(assigns(:assumption)).to be_persisted
      end

      it "redirects to the created assumption" do
        post :create, {:assumption => valid_attributes}, valid_session
        expect(response).to redirect_to(Assumption.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved assumption as @assumption" do
        post :create, {:assumption => invalid_attributes}, valid_session
        expect(assigns(:assumption)).to be_a_new(Assumption)
      end

      it "re-renders the 'new' template" do
        post :create, {:assumption => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested assumption" do
        assumption = Assumption.create! valid_attributes
        put :update, {:id => assumption.to_param, :assumption => new_attributes}, valid_session
        assumption.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested assumption as @assumption" do
        assumption = Assumption.create! valid_attributes
        put :update, {:id => assumption.to_param, :assumption => valid_attributes}, valid_session
        expect(assigns(:assumption)).to eq(assumption)
      end

      it "redirects to the assumption" do
        assumption = Assumption.create! valid_attributes
        put :update, {:id => assumption.to_param, :assumption => valid_attributes}, valid_session
        expect(response).to redirect_to(assumption)
      end
    end

    context "with invalid params" do
      it "assigns the assumption as @assumption" do
        assumption = Assumption.create! valid_attributes
        put :update, {:id => assumption.to_param, :assumption => invalid_attributes}, valid_session
        expect(assigns(:assumption)).to eq(assumption)
      end

      it "re-renders the 'edit' template" do
        assumption = Assumption.create! valid_attributes
        put :update, {:id => assumption.to_param, :assumption => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested assumption" do
      assumption = Assumption.create! valid_attributes
      expect {
        delete :destroy, {:id => assumption.to_param}, valid_session
      }.to change(Assumption, :count).by(-1)
    end

    it "redirects to the assumptions list" do
      assumption = Assumption.create! valid_attributes
      delete :destroy, {:id => assumption.to_param}, valid_session
      expect(response).to redirect_to(assumptions_url)
    end
  end

end
