require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AssumptionsController, type: :controller do
  login_admin
  # This should return the minimal set of attributes required to create a valid
  # Assumption. As you add validations to Assumption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:test_assumption).attributes
  }

  let!(:assumption) { create(:test_assumption) }
  subject { assumption }
  let(:invalid_attributes) {
    {test_assumption: {name: ""}}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssumptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all assumptions as @assumptions" do
      get :index, {}, valid_session
      expect(assigns(:assumptions)).to eq([subject])
    end
  end

  describe "GET #show" do
    it "assigns the requested assumption as @assumption" do
      get :show, {:id => subject.to_param}, valid_session
      expect(assigns(:assumption)).to eq(subject)
    end
  end

  describe "GET #new" do
    it "assigns a new assumption as @assumption" do
      get :new, {}, valid_session
      expect(assigns(:assumption)).to be_a_new(Assumption)
    end
  end

  describe "GET #edit" do
    it "assigns the requested assumption as @assumption" do
      get :edit, {:id => subject.to_param}, valid_session
      expect(assigns(:assumption)).to eq(subject)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Assumption" do
        expect {
          post :create, {:test_assumption => valid_attributes}, valid_session
        }.to change(Assumption, :count).by(1)
      end

      it "assigns a newly created assumption as @assumption" do
        post :create, {:test_assumption => valid_attributes}, valid_session
        expect(assigns(:assumption)).to be_a(Assumption)
        expect(assigns(:assumption)).to be_persisted
      end

    end

    context "with invalid params" do
      it "assigns a newly created but unsaved assumption as @assumption" do
        post :create, {:test_assumption => invalid_attributes}, valid_session
        expect(assigns(:assumption)).to be_a_new(Assumption)
      end

      it "re-renders the 'new' template" do
        post :create, {:test_assumption => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: "Test"}
      }

      it "updates the requested assumption" do
        put :update, {:id => assumption.to_param, :test_assumption => new_attributes}, valid_session
        assumption.reload
        expect(assumption.name).to eq("Test")
      end

      it "assigns the requested assumption as @assumption" do
        put :update, {:id => assumption.to_param, :test_assumption => valid_attributes}, valid_session
        expect(assigns(:assumption)).to eq(assumption)
      end

      it "redirects to the assumption" do
        put :update, {:id => assumption.to_param, :test_assumption => valid_attributes}, valid_session
        expect(response).to redirect_to(assumption)
      end
    end

    context "with invalid params" do
      it "assigns the assumption as @assumption" do
        put :update, {:id => assumption.to_param, :test_assumption => invalid_attributes}, valid_session
        expect(assigns(:assumption)).to eq(assumption)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested assumption" do
      expect {
        delete :destroy, {:id => assumption.to_param}, valid_session
      }.to change(Assumption, :count).by(-1)
    end

    it "redirects to the assumptions list" do
      delete :destroy, {:id => assumption.to_param}, valid_session
      expect(response).to redirect_to(assumptions_url)
    end
  end

end
